# Generated by Django 5.2.6 on 2025-09-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("summary", models.TextField()),
                ("technologies", models.CharField(max_length=255)),
                ("image", models.ImageField(blank=True, upload_to="project_images/")),
                ("featured", models.BooleanField(default=False)),
            ],
        ),
    ]
